### ISSUE TITLE
Request: File name matching mod name

### ISSUE THREAD

**Issue by NillerMedDild** [Lothrazar/LadderPower#1]
I thought I'd skip the template as it's not relevant, hope that's alright.

Basically I would like the jar name to be at least similar to the mod's name, so I can easily tell which mods are which.

Jar name is `railladderpower-1.15.2-1.0.0`, CurseForge name is `Scaffolding Behaviour`

**Comment by Lothrazar** [comment]
Also the config file is "ladderpower.toml" which is confusing.

Maybe its still early enough to change the modID so its all consistent

**Comment by Lothrazar** [comment]
will be "scaffoldingpower" jar file and "scaffoldingpower.toml" config to match

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/scaffolding-behavior/files/2915437

**Comment by NillerMedDild** [comment]
Perfect, thanks :)
