### ISSUE TITLE
[Request] Also affect Powered Rail

### ISSUE THREAD

**Issue by NillerMedDild** [Lothrazar/LadderPower#2]
Pretty much the title, I'd like the behaviour to also work with other tracks, especially Powered Rail :)

It works great btw, thanks for another nice mod.

**Comment by Lothrazar** [comment]
Latest 1.1.0 update treats all rails the same now using the "#minecraft:rails" item tag

**Comment by Lothrazar** [comment]
Wait i just realized i havent released 1.1.0, thought it was out. ok coming soon
